### ISSUE TITLE
Change ca-fingerprint flag to expect SHA-256 digest instead of MD5

### ISSUE THREAD

**Issue by omorsi** [micromdm/scep#156]
This is to complete pull request #144 which should have removed all weak hash functions usages.

https://github.com/micromdm/scep/blob/c89253406d2e73be69933382e1c0aed9069283be/cmd/scepclient/scepclient.go#L271

**Comment by jessepeterson** [comment]
This seems appropriate for the `CertsSelector` interface you made in #147.

**Comment by omorsi** [comment]
Yup! So to make sure I understand your suggestion, do you agree on the following?

- Change ca-fingerprint to be expecting SHA-256 instead of MD5. 
- Add a fingerprintCertsSelector(sha256 string) that selects only the cert with this fingerprint.
- Use this selector with the value of flag: ca-fingerprint.

WDYT?

**Comment by jessepeterson** [comment]
In short: yes.

But because this feature, as I understand it, is directly related to supporting NDES is why it is MD5 in the first place — Microsoft shows an MD5 or SHA1 "thumbprint" by default: https://blog.keyfactor.com/the-ndes-ca-thumbprint-hash

However I'm okay with using SHA2 and just letting folks either find the SHA2 of their CA themselves or writing their own custom `CertsSelector` that uses MD5/SHA1/whatever. Maybe some day `scepclient` could have a `-dumpca` which just dumps the PEM CAs and SHA256's of the `GetCACert` as a helper.

**Comment by jessepeterson** [comment]
Oh also of note (related, but not directly) macOS has the `CAFingerprint` field in their SCEP profile: https://developer.apple.com/documentation/devicemanagement/scep/payloadcontent  This is a raw binary hash of the cert it wants to use — analogous to this CLI switch. While documentation is slim I'm pretty sure it selects the hash algo based on the length of the data (i.e. 20 bytes is a SHA-1).

**Comment by omorsi** [comment]
Thanks so much for the info :) Ok! I will create a PR for that.
