### ISSUE TITLE
Scepclient assumes that GetCaCerts returns certificates in order 

### ISSUE THREAD

**Issue by omorsi** [micromdm/scep#159]
Noticed that the function findRecepients [*] that is used to filter certificates by the fingerprint provided as a flag assumes that the certificates returned from GetCaCerts constitutes a valid certificates chain. I didn't find this explicitly mentioned in SCEP ietfs, is it safe to assume that?

[*] https://github.com/omorsi/scep/blob/c89253406d2e73be69933382e1c0aed9069283be/cmd/scepclient/scepclient.go#L227

**Comment by jessepeterson** [comment]
Hmm, good catch. I'm not sure anything other than a single P7 recipient makes sense.

[SCEP 23 § 3.1.2](https://tools.ietf.org/html/draft-nourse-scep-23#section-3.1.2) says:

> The PKCS#7 [RFC2315] content-encryption key (see Section 10, step 2) is encrypted using the public key of **THE** recipient of the message, i.e. the RA or the CA public key (if sent from the requester), or **THE** requester public key (if sent as a reply to the requester).

(Emphasis added)

This heavily implies to me that we should only be sending a single recipient to the P7 library to encrypt the content. So I'm inclined to think a full chain isn't implied.

What do you propose? Seems more correct to me to be returning a single cert rather than a subset — or assuming any order in which they're returned.

**Comment by omorsi** [comment]
> Seems more correct to me to be returning a single cert rather than a subset — or assuming any order in which they're returned.

I agree! Will create a PR with that.
