### ISSUE TITLE
Log pattern improvements

### ISSUE THREAD

**Issue by klubi** [micromdm/scep#181]
Hi

I'm setting up SCEP Server in kubernetes infrastructure, including log gathering and monitoring.
Current log format makes it extremely hard to prepare logging solution that would allow to precisely parse logs and divide into fields.
This is an example of grok filter I came up with in order to divide log records into searchable fields.
```
level=%{LOGLEVEL:level}\s*ts=%{TIMESTAMP_ISO8601:timestamp}\s*(caller=(?<caller>[a-z_]+(.go:)[0-9]+) )?(component=(?<component>[a-z_]+) )?(op=(?<op>[a-zA-Z]+) )?(method=(?<method>[a-zA-Z]+) )?((message|msg)=(("%{DATA:message}")|null|) )?((error|err)=(("%{GREEDYDATA:error})"|null))?(\s*)?(status=%{INT:http_status} )?(proto=%{DATA:http_version} )?(host=%{IP:ip} )?(user_agent=%{DATA:user_agent} )?(took=(?<took>[0-9\.]+[µnm]s))?(path="%{DATA:path}")?
```
As you can see most fields are optional capture groups that may or may not be present in log.

Would it be possible to use one pattern?

Thanks!

EDIT:
I updated above grok pattern, because it wasn't capturing all lines.

I also found cases, where lor line does not contain `level` field:
```
ts=2022-02-28T07:25:57.920676662Z caller=service.go:88 msg="failed to sign CSR" err="invalid challenge"
ts=2022-02-15T16:09:39.574738039Z caller=service.go:88 msg="failed to sign CSR" err="open depot/asd.2.pem: file exists"
```

Would be great if log level was included in every log line, this would make log parsing way easier.

**Comment by jessepeterson** [comment]
It looks like you're trying to depend on how the log lines are output. I'd advise against this. Logging is done as arbitrary key-value pairs which may or may not be present in any given log output lines. This project uses structured logging and the default server output is in the [logfmt](https://brandur.org/logfmt) format.  One option would be to output JSON logs instead of logfmt, if that'd be helpful. Another option wold be for you to to fork the project, adapt the [go-kit logger](https://github.com/go-kit/log) interfaces and log however you see fit (though, again, you'll just have to deal with key-value pairs there, too). Yet another if you don't want to modify any Go code would be use a proper logfmt parser instead of trying to parse the raw log output line. I don't think we'll be optimizing anything for parsing the _output string_ format of the logfmt output. Happy to reconsider, though. Feel free to re-open if you'd like to see some other outcome here. :)
